# Generated by Django 5.1.4 on 2025-01-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Groceries',
        ),
    ]
