# Generated by Django 5.1.4 on 2025-01-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
    ]
