# Generated by Django 5.1.4 on 2025-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Computer Science', max_length=50),
            preserve_default=False,
        ),
    ]
